// Mocks generated by Mockito 5.4.6 from annotations
// in kincare/test/unit/domain/usecases/get_medications_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kincare/core/errors/result.dart' as _i4;
import 'package:kincare/domain/entities/medication_entity.dart' as _i5;
import 'package:kincare/domain/repositories/medication_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MedicationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationRepository extends _i1.Mock
    implements _i2.MedicationRepository {
  @override
  _i3.Future<_i4.Result<List<_i5.MedicationEntity>>> getMedications() =>
      (super.noSuchMethod(
            Invocation.method(#getMedications, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.MedicationEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.MedicationEntity>>>(
                    this,
                    Invocation.method(#getMedications, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i5.MedicationEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.MedicationEntity>>>(
                    this,
                    Invocation.method(#getMedications, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.MedicationEntity>>>);

  @override
  _i3.Future<_i4.Result<_i5.MedicationEntity>> createMedication(
    _i5.MedicationEntity? medication,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMedication, [medication]),
            returnValue: _i3.Future<_i4.Result<_i5.MedicationEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.MedicationEntity>>(
                this,
                Invocation.method(#createMedication, [medication]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i5.MedicationEntity>>.value(
                  _i6.dummyValue<_i4.Result<_i5.MedicationEntity>>(
                    this,
                    Invocation.method(#createMedication, [medication]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.MedicationEntity>>);

  @override
  _i3.Future<_i4.Result<_i5.MedicationEntity>> updateMedication(
    _i5.MedicationEntity? medication,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMedication, [medication]),
            returnValue: _i3.Future<_i4.Result<_i5.MedicationEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.MedicationEntity>>(
                this,
                Invocation.method(#updateMedication, [medication]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i5.MedicationEntity>>.value(
                  _i6.dummyValue<_i4.Result<_i5.MedicationEntity>>(
                    this,
                    Invocation.method(#updateMedication, [medication]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.MedicationEntity>>);

  @override
  _i3.Future<_i4.Result<void>> deleteMedication(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMedication, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteMedication, [id]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteMedication, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
